version: '3.8'

services:
  # Service PHP pour l'application Laravel
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tourshop-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - tourshop-network

  # Service Nginx pour le serveur web
  nginx:
    image: nginx:latest
    container_name: tourshop-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tourshop-network

networks:
  tourshop-network:
    driver: bridge