services:
  # Service PHP-Apache (Local Development)
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tourshop-app
    restart: unless-stopped
    ports:
      - "8000:80" # Map port 80 (inside) to 8000 (outside)
    environment:
      - PORT=80
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - tourshop-network

networks:
  tourshop-network:
    driver: bridge