services:
  # Service unique combinant PHP et Serveur Web (Apache)
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tourshop-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - tourshop-network

networks:
  tourshop-network:
    driver: bridge